const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)],STATIC_DEMO=location.hostname==='stina.tech'||location.hostname==='www.stina.tech'||location.hostname.endsWith('.github.io')||location.protocol==='file:';let admin=null,reservations=[],overview=null,currentReservation=null;
async function api(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const type=res.headers.get('content-type')||'',data=type.includes('json')?await res.json():await res.text();if(!res.ok)throw new Error(data.error||'Request failed');return data}
function message(text,error=false){const t=$('.admin-toast');t.textContent=text;t.style.background=error?'#9b4242':'';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-auth-form]').forEach(f=>f.classList.toggle('active',f.dataset.authForm===b.dataset.authTab));$('.auth-error').textContent=''});
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await init()}catch(err){$('.auth-error').textContent=err.message}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/register',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});message('Administrator created. You can now sign in.');$('[data-auth-tab=login]').click()}catch(err){$('.auth-error').textContent=err.message}};
$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};
async function init(){if(STATIC_DEMO)return;try{const me=await api('/api/admin/me');admin=me.admin;$('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#adminName').textContent=admin.name;$('#adminInitial').textContent=admin.name[0].toUpperCase();await loadOverview();await loadReservations()}catch{$('#auth').classList.remove('hidden');$('#dashboard').classList.add('hidden')}}
function date(v){return v?new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(v)):'—'}function datetime(v){return v?new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—'}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function status(v){return `<span class="status ${esc(v)}">${esc(v.replaceAll('_',' '))}</span>`}
async function loadOverview(){overview=await api('/api/admin/overview');const c=overview.counts;$('#metricTotal').textContent=c.total;$('#metricNew').textContent=c.new;$('#metricConfirmed').textContent=c.confirmed;$('#metricCancel').textContent=c.cancellationRequested;$('#arrivalsToday').textContent=c.arrivingToday;$('#newBadge').textContent=c.new;$('#cancelBadge').textContent=c.cancellationRequested;$('#serverClock').textContent='Updated '+new Date(overview.serverTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('#recentList').innerHTML=overview.recent.length?overview.recent.map(r=>`<button data-open-id="${r.id}"><b>${esc(r.fullName)}<small>${esc(r.reference)}</small></b><span>${date(r.checkIn)} → ${date(r.checkOut)}</span>${status(r.status)}</button>`).join(''):'<p>No reservation requests yet.</p>';$('#miniAudit').innerHTML=overview.audit.slice(0,5).map(a=>auditRow(a)).join('');$('#auditList').innerHTML=overview.audit.map(a=>auditRow(a,true)).join('');bindOpen()}
function auditRow(a,full=false){return `<div class="audit-row"><span>${datetime(a.at)}</span>${full?`<b>${esc(a.action.replaceAll('_',' '))}</b>`:''}<b>${esc(a.target||'System')}</b><span>${esc(a.details||a.action.replaceAll('_',' '))}</span></div>`}
async function loadReservations(){const search=encodeURIComponent($('#searchReservations').value||''),st=encodeURIComponent($('#statusFilter').value||'all'),data=await api(`/api/admin/reservations?search=${search}&status=${st}`);reservations=data.reservations;renderRows();renderCancellations()}
function renderRows(){const body=$('#reservationRows');body.innerHTML=reservations.map(r=>`<tr><td><b>${esc(r.reference)}</b><small>${esc(r.source)}</small></td><td><b>${esc(r.fullName)}</b><small>${esc(r.email)} · ${esc(r.phone)}</small></td><td><b>${date(r.checkIn)} → ${date(r.checkOut)}</b><small>${r.guests} guest${r.guests===1?'':'s'}</small></td><td>${esc(r.roomType)}</td><td>${status(r.status)}</td><td>${datetime(r.createdAt)}</td><td><button class="open-row" data-open-id="${r.id}">Open →</button></td></tr>`).join('');$('#emptyRows').classList.toggle('hidden',reservations.length>0);bindOpen()}
function renderCancellations(){const rows=reservations.filter(r=>r.status==='cancellation_requested');$('#cancellationGrid').innerHTML=rows.length?rows.map(r=>`<article class="cancel-card"><small>${esc(r.reference)}</small><h3>${esc(r.fullName)}</h3><p>${date(r.checkIn)} → ${date(r.checkOut)}<br>${esc(r.email)} · ${esc(r.phone)}</p><p>${esc(r.history?.[0]?.note||'Cancellation requested')}</p><button data-open-id="${r.id}">Review request →</button></article>`).join(''):'<div class="panel">No cancellation requests are waiting.</div>';bindOpen()}
function bindOpen(){$$('[data-open-id]').forEach(b=>b.onclick=()=>openReservation(b.dataset.openId))}
async function openReservation(id){currentReservation=reservations.find(r=>r.id===id)||overview?.recent.find(r=>r.id===id);if(!currentReservation){await loadReservations();currentReservation=reservations.find(r=>r.id===id)}const r=currentReservation;if(!r)return;$('#drawerContent').innerHTML=`<div class="drawer-head"><small>${esc(r.reference)}</small><h2>${esc(r.fullName)}</h2>${status(r.status)}</div><div class="drawer-grid"><span>Stay<b>${date(r.checkIn)} → ${date(r.checkOut)}</b></span><span>Room<b>${esc(r.roomType)} · ${r.guests} guest(s)</b></span><span>Contact<b>${esc(r.email)}<br>${esc(r.phone)}</b></span><span>Arrival<b>${esc(r.arrivalTime||'Not specified')}</b></span></div><section class="drawer-section"><h3>Guest request</h3><p>${esc(r.requests||'No special requests.')}</p></section><section class="drawer-section"><h3>Update status</h3><select id="drawerStatus">${['new','contacted','confirmed','cancellation_requested','cancelled','checked_in','completed','no_show'].map(s=>`<option value="${s}" ${s===r.status?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select><input id="statusNote" placeholder="Reason or action note"><div class="drawer-actions"><button id="saveStatus">Save status</button></div></section><section class="drawer-section"><h3>Internal notes</h3><textarea id="adminNotes" rows="5" placeholder="Visible to administrators only">${esc(r.adminNotes||'')}</textarea><div class="drawer-actions"><button id="saveNotes">Save notes</button></div></section><section class="drawer-section"><h3>History</h3>${(r.history||[]).map(h=>`<div class="history-item"><b>${esc(h.status.replaceAll('_',' '))}</b><span>${datetime(h.at)} · ${esc(h.by)}</span><p>${esc(h.note)}</p></div>`).join('')}</section>`;$('#reservationDrawer').classList.add('open');$('.drawer-backdrop').classList.add('open');$('#saveStatus').onclick=()=>updateReservation({status:$('#drawerStatus').value,note:$('#statusNote').value});$('#saveNotes').onclick=()=>updateReservation({adminNotes:$('#adminNotes').value})}
async function updateReservation(payload){try{await api('/api/admin/reservations/'+currentReservation.id,{method:'PATCH',body:JSON.stringify(payload)});message('Reservation updated');closeDrawer();await loadOverview();await loadReservations()}catch(err){message(err.message,true)}}
function closeDrawer(){$('#reservationDrawer').classList.remove('open');$('.drawer-backdrop').classList.remove('open')}$('.drawer-close').onclick=closeDrawer;$('.drawer-backdrop').onclick=closeDrawer;
const viewMeta={overview:['OPERATIONS AT A GLANCE','Overview'],reservations:['GUEST REQUESTS','Reservations'],cancellations:['PRIORITY ACTION','Cancellations'],audit:['RELIABILITY & TRACEABILITY','Activity log']};function goView(name){$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));$('#viewKicker').textContent=viewMeta[name][0];$('#viewTitle').textContent=viewMeta[name][1];if(name==='cancellations'){$('#statusFilter').value='all';loadReservations()}}
$$('[data-view]').forEach(b=>b.onclick=()=>goView(b.dataset.view));$('[data-go-reservations]').onclick=()=>goView('reservations');let searchTimer;$('#searchReservations').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadReservations,250)};$('#statusFilter').onchange=loadReservations;$('#refresh').onclick=async()=>{await loadOverview();await loadReservations();message('Dashboard refreshed')};
init();setInterval(()=>{if(admin)loadOverview().catch(()=>$('#apiDot').style.background='#b45151')},60000);
