(() => {
 const copy=n=>window.REDC2_PRINT_DIAGRAMS[n]||'';
 const data=window.REDC2_CONTENT;
 const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
 const crop=(src,width,x,y,w,h,alt)=>`<div class="detail-window" style="aspect-ratio:${w}/${h};height:auto"><img src="${src}" alt="${alt}" style="width:${width/w*100}%;left:${-x/w*100}%;top:${-y/h*100}%"></div>`;
 const web=n=>`assets/ui/webrecon/${n}.png`;
 const capture=id=>window.REDSHADES_CAPTURES.find(item=>item.id===id);
 const shot=(id,coordinates)=>{const item=capture(id);return crop(item.src,item.width,...(coordinates||item.detail),item.caption);};
 const overview=id=>{const item=capture(id);return `<img class="capture-overview" src="${item.src}" width="${item.width}" height="${item.height}" alt="${item.caption}">`;};
 const plate=(id,coordinates)=>{const item=capture(id);return `<div class="capture-plate"><div class="capture-context">${overview(id)}<p class="capture-annotation"><b>Overview</b>${item.caption}</p></div><div class="capture-detail">${shot(id,coordinates)}<p class="capture-annotation"><b>Detail</b>${item.provenance}</p></div></div>`;};
 const flow=items=>`<div class="technical-flow">${items.map(([h,t],i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><section><h3>${h}</h3><p>${t}</p></section></div>`).join('')}</div>`;
 const table=(headers,rows)=>`<table class="technical-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<${i?'td':'th'}>${v}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table>`;
 const diagram=(labels,subtitles)=>`<svg viewBox="0 0 800 350" role="img" aria-label="${labels.join(', ')}"><g fill="none" stroke="#bd4836" stroke-width="3"><path d="M170 170H330M470 170H630"/></g>${labels.map((l,i)=>`<rect x="${20+i*280}" y="95" width="200" height="150" fill="#eef1e8" stroke="#739081"/><text x="${120+i*280}" y="156" text-anchor="middle" fill="#173d32" font-size="23" font-weight="700">${l}</text><text x="${120+i*280}" y="194" text-anchor="middle" fill="#4d6459" font-size="17">${subtitles[i]}</text>`).join('')}</svg>`;
 const visuals={
 6:{kind:'domain',html:`<div class="domain-grid">${[['Identity','Realm · principal · typed secrets'],['Authority','Scope · credentials · gates'],['Evidence','Custody · provenance · artifact roles'],['Execution','Actions · requests · receipts'],['Recovery','Resources · frontier · lineage'],['Revision','Reference closure · valid transitions']].map(([h,t])=>`<div><h3>${h}</h3><p>${t}</p></div>`).join('')}</div><div class="domain-boundary">Complete engagement revision</div>`,caption:'Related records are validated and persisted within one revision.'},
 7:{kind:'process',html:flow([['Validate state','Reference closure and legal transitions'],['Check the head','Expected revision and parent generation'],['Build the generation','Content and envelope digests'],['Commit atomically','Generation, compatibility records, and head']]),caption:'Checkpoint publication occurs within one PostgreSQL transaction.'},
 8:{kind:'table',html:table(['Condition','Recorded meaning'],[['Queued','Work exists; execution has not begun.'],['Running','A current owner holds the attempt and progress lease.'],['Interrupted','Nonterminal work has lost its runtime owner.'],['Unknown outcome','An effect may have occurred; observation or reconciliation is required.'],['Terminal','Completed, failed, or cancelled retains its final outcome.']]),caption:'Lifecycle states preserve ownership loss and unresolved outcomes.'},
 9:{kind:'diagram',html:diagram(['Prepared intent','Execution','Outcome'],['baseline + revision','typed receipt','read-back evidence']),caption:'Intent, dispatch, and observed result retain separate records.'},
 10:{kind:'diagram',html:copy(14,'svg'),caption:'Raw custody serves multiple compact projections and source views.'},
 11:{kind:'table',html:table(['Context dimension','Retained facts'],[['Identity','Principal, credentials, delegated authority'],['Placement','Host, process, isolation boundary, session'],['Reachability','Interface, route, tunnel, relay'],['Policy','Applicable scope and gate references'],['Validity','Observed, unavailable, not applicable, stale, or conflicted']]),caption:'Each factual dimension has its own observation status and time.'},
 12:{kind:'diagram',html:copy(13,'svg'),caption:'Specialist output passes through a typed adapter into a compact projection.'},
 13:{kind:'table',html:table(['Source family','Bounded navigation coordinates'],[['Packet / protocol','Packet selection, filters, and ranges'],['Binary / debug','Address space, image base, and selected range'],['Artifact / mobile','Artifact identity and bounded source coordinates'],['HTTP / browser','Source evidence, request/response identity, and selection'],['Environment','Process, namespace, session, and context transition']]),caption:'A source-viewer handoff binds retained custody to the intended selection.'},
 14:{kind:'process',html:flow([['Bound inputs','Exact source records and their revisions'],['Versioned transform','Deterministic operation and parameters'],['Derived result','Typed output with bounded custody'],['Derivation history','Inputs, results, deltas, and retained lineage']]),caption:'Derived analysis preserves the relationship to its source records.'},
 15:{kind:'process',html:flow([['Bind the plan','Recipe, source, context, scope, and preview'],['Resolve prerequisites','Inputs, adapter availability, and exact approval'],['Checkpoint each step','Retain every verified completed result'],['Recover the prefix','Preserve completed work; reconcile interruption']]),caption:'Ordered experiment steps retain independently recoverable checkpoints.'},
 16:{kind:'table',html:table(['Eligibility input','Required condition'],[['Capability','Verified, applicable evidence'],['Resource','Current health and valid dependency'],['Context','Exact identity, placement, route, and scope'],['Decision','Deterministically validated receipt'],['Lease','Owner and generation; heartbeat, progress, and overall deadlines']]),caption:'The frontier records eligibility and blockers against an expected revision.'},
 17:{kind:'process',html:flow([['Canonical evidence','Revision-bound packet and typed request'],['Provider work','Bounded reasoning under supervised ownership'],['Deterministic validation','Identity, references, schema, and applicability'],['Decision receipt','Durable result for policy and application services']]),caption:'A provider response becomes usable through deterministic validation.'},
 18:{kind:'table',html:table(['Worker boundary','Binding'],[['Input','Immutable request envelope and input hash'],['Artifact','Exact admitted worker identity'],['Ownership','Provider generation and live resource lease'],['Output','Typed records and custody references'],['Recovery','Cancellation cause, cleanup, and retained result state']]),caption:'Worker inputs and results remain bound to admitted code and current ownership.'},
 19:{kind:'process',html:flow([['Define','Typed service contract and dependencies'],['Prepare','Unpublished scope with recorded effects'],['Publish','Atomic generation visibility'],['Lease','Exact generation retained by each consumer'],['Drain','Bounded reverse cleanup after release']]),caption:'The kernel manages provider availability through one ownership model.'},
 20:{kind:'diagram',html:copy(17,'svg'),caption:'Existing calls retain generation A while new resolutions use generation B.'},
 21:{kind:'table',html:table(['Resource fact','Question answered'],[['Desired state','Should the managed resource exist?'],['Ownership','Which supervisor and generation hold it?'],['Health','Has a named, bounded observation succeeded recently?'],['Applicability','Can this resource support the exact work and context?']]),caption:'Availability depends on four independently recorded resource facts.'},
 22:{kind:'process',html:flow([['Observe and classify','Retain the incident and select its repair owner'],['Repair session','Scoped source work with persistent incident history'],['Validate and admit','Independent evidence and deterministic admission'],['Replace and hand back','Component swap and verified return to interrupted work']]),caption:'AEP retains ownership from the accepted incident through verified hand-back.'},
 23:{kind:'diagram',html:diagram(['Contract','Candidate','Admission'],['scoped capability','digest-bound artifacts','validation receipts']),caption:'A generation session retains candidate artifacts and their admission evidence.'},
 24:{kind:'diagram',html:copy(24,'svg'),caption:'Production control and authoritative reads surround a simulated process boundary.'},
 25:{kind:'table',html:table(['Run 1599 gate','Documented result'],[['Cache custody','Passed'],['Overlay','Passed'],['PostgreSQL','Passed'],['Root contracts','Three failures'],['Process cleanup','Ambient CLI process tree retained']]),caption:'Latest documented pushed Go receipt; subsequent repairs await a new result.',label:'Documented CI status'},
 26:{kind:'process',html:flow([['Stage the set','Complete component files in a private incoming set'],['Verify','Manifest, source revision, digest, and readiness'],['Preflight','Paired Go and Qt ABI compatibility'],['Publish or restore','Atomic replacement with explicit rollback status']]),caption:'Artifact integrity and compatibility are checked before publication.'},
 27:{kind:'measurement',html:`<div class="measurement"><div class="measurement-value">71,462<span>dirty pixels</span></div><div class="measurement-viewport"><span>921,600-pixel viewport</span><i></i></div></div>`,caption:'Dirty-region update in the retained operator fixture: 71,462 of 921,600 pixels.',label:'Historical measurement · July 2026'},
 28:{kind:'diagram',html:copy(36,'svg'),caption:'Versioned state flows to Qt; attributed intent returns to Go.'},
 29:{kind:'table',html:table(['Underlying contract','Technical capability'],[['Canonical state','Consistent recovery and evidence inspection'],['Typed custody','Fidelity-preserving source navigation'],['Revisioned decisions','Scoped review and attributed continuation'],['Generation leases','Component replacement with retained ownership'],['TMG / SCG','Evidence-bound hypotheses and prerequisite diagnostics'],['Native projections','Responsive graph inspection and bounded detail']]),caption:'Operator capabilities derive from shared state and interface contracts.'},
 30:{kind:'gallery',html:`<div class="print-gallery">${crop('assets/ui/operator/internal_sessions_1920x1080.png',1920,12,685,760,205,'Actual Qt sessions workspace detail with synthetic data')}<p class="image-credit">Sessions workspace with synthetic project data.<span>Qt capture · synthetic fixture</span></p>${copy(27,'svg')}<p class="image-credit">Dependencies, concurrent work, and a local review gate.<span>Conceptual diagram</span></p></div>`,caption:''},
 31:{kind:'gallery',html:crop('assets/ui/network/topology-synthetic.png',1600,450,490,790,350,'Actual Network Graph with synthetic host and session data'),caption:'Network Graph with synthetic host and session data.',label:'Qt capture · synthetic fixture'},
 32:{kind:'gallery',html:`<div class="webrecon-plate">${crop(web('overview'),1536,295,300,870,290,'Actual WebRecon evidence linked by navigation and response relationships')}<p class="image-credit">Web evidence linked by navigation and response relationships.<span>Qt capture · synthetic fixture</span></p>${crop(web('gated'),1536,1170,265,345,116,'Actual selected evidence and a pending endpoint review')}<p class="image-credit">Selected evidence and a pending endpoint review.<span>Qt capture · synthetic fixture</span></p></div>`,caption:''},
 33:{kind:'diagram',html:copy(32,'svg'),caption:'A conclusion linked to supporting observations and counter-evidence.'},
 34:{kind:'table',html:table(['Workbench record','Inspection and continuation'],[['Canonical detail','Stable identity, revision, evidence, and custody'],['Source navigation','Packet, binary, artifact, and environment coordinates'],['Context timeline','Identity, placement, route, scope, and transitions'],['Pending reconciliation','Separate attributed acceptance or rejection'],['Accepted intent','Exact command identity retained across interruption']]),caption:'Canonical record detail, source navigation, and pending reconciliation.'},
 35:{kind:'process',html:flow([['Contract review','Declared behavior and proposed methodology'],['Parser or stage fixture','Supplied inputs and local transitions'],['Orchestration simulation','Production state and coordination under controlled failure'],['Representative live lab','Real tools, processes, services, and operating systems'],['Broader acceptance','Unusual configurations and sustained integration']]),caption:'Each evaluation level introduces dependencies absent from the previous level.'},
 36:{kind:'research',html:copy(21,'svg'),caption:'Training disclosures and cumulative represented families.',label:'Versioned study · 200 training records'},
 37:{kind:'table',html:table(['Retained evidence','Scope'],[['Backend / operator','Persistence, lifecycle, specialist contracts, rendering, integrity'],['18/18 runs','Three production discovery scenarios'],['40/40 runs','Reusable synthetic mechanics'],['Reported field outcomes','Autonomous completions; exact outcome logs unavailable']]),caption:'The retained records distinguish engineering checks, simulation, and field reports.',label:'Evidence classes'},
 38:{kind:'table',html:table(['Boundary','Remaining limitation'],[['Legacy adoption','Canonical scheduler and AI integration remains incomplete'],['Authority','Some legacy stages follow a single launch approval'],['Adapter breadth','Authentic exports and representative environments remain necessary'],['Recovery','Projection outages, browser descendants, and unusual environments'],['AEP / research','Unfamiliar-failure convergence and wider generalization remain unproven']]),caption:'Current limitations retain distinct implementation and evaluation scopes.'},
 39:{kind:'process',html:flow([['Canonical adoption','Scheduler, supervised AI, and repaired CI contracts'],['Environmental verification','Ownership loss, outages, archived state, and adapter fidelity'],['Repair-loop evaluation','Incident history, independent validation, and hand-back'],['Research generalization','Unrelated evidence and unchanged held-out cohorts']]),caption:'Development priorities are tied to specific unresolved evidence requirements.'}
 };
 const previous={...visuals};
 Object.assign(visuals,{
  30:{kind:'gallery',html:`<div class="shell-sequence">${crop('assets/ui/operator/internal_sessions_1920x1080.png',1920,12,685,760,205,'Qt sessions workspace with synthetic state')}<p class="image-credit">Sessions · Qt capture · synthetic fixture</p>${crop('assets/ui/operator/internal_agents_1280x900.png',1280,12,640,900,248,'Qt agents workspace with synthetic records')}<p class="image-credit">Agents · Qt capture · synthetic fixture</p>${crop('assets/ui/operator/internal_listeners_1280x900.png',1280,12,640,900,248,'Qt listeners workspace with synthetic records')}<p class="image-credit">Listeners · Qt capture · synthetic fixture</p></div>`,caption:'Native workspaces retain separate session, agent and listener records.',label:'Qt captures · synthetic fixtures'},
  31:{kind:'diagram',html:copy(27),caption:'Dependencies connect concurrent work to read-back and local review.'},
  32:{kind:'table',html:table(['Inspection domain','Bounded canonical detail'],[['Identity','Exact plan-node and runtime identities'],['Evidence','Stable source references and custody'],['Dependencies','Eligibility and explicit blocker reasons'],['Context','Principal, host, route, scope and validity'],['Action','Expected revision, gate and consequences'],['History','Attempts, checkpoints and cancellation cause']]),caption:'Node detail is resolved against an exact canonical identity.'},
  33:previous[31],
  34:{kind:'gallery',html:`<div class="web-sequence">${crop(web('overview'),1536,270,280,900,400,'WebRecon overview with synthetic evidence cards')}<p class="image-credit">Evidence relationships · Qt capture · synthetic fixture</p>${crop(web('preview'),1536,240,230,750,640,'WebRecon selected source preview with synthetic evidence')}<p class="image-credit">Selected source preview.<br>Qt capture · synthetic fixture.<br><br>The preview is attached to its evidence record and retains the source selection.</p></div>`,caption:'Stable evidence identities connect observations to their retained source.',label:'Qt captures · synthetic fixtures'},
  35:{kind:'gallery',html:`${crop(web('gated'),1536,1170,265,345,116,'Actual pending WebRecon endpoint review gate')}<p class="image-credit">Endpoint review · Qt capture · synthetic fixture</p>${diagram(['Endpoint A','Endpoint B','Hypothesis'],['local browser review','independent worker','BHG policy review'])}`,caption:'Endpoint review is local to its worker; BHG is a separate hypothesis-policy boundary.',label:'Qt capture + conceptual diagram'},
  36:previous[33],37:previous[34],
  38:{kind:'process',html:flow([['Inspect the checkpoint','Retained work, context and exact identity'],['Check ownership','Current generation and resource availability'],['Reconcile','Attributed acceptance or rejection'],['Continue','Revisioned action with a durable receipt']]),caption:'RCC binds recovery to factual context and an explicit decision.'},
  39:previous[35],40:previous[36],
  41:{kind:'domain',html:`<div class="research-triptych"><section><strong>R</strong><h3>Representability</h3><p>Can the vocabulary express the procedure?</p></section><section><strong>E</strong><h3>Executability</h3><p>Are inputs, executor, policy and validation available?</p></section><section><strong>D</strong><h3>Derivability</h3><p>Does the supplied evidence contain sufficient mechanics?</p></section></div><div class="study-counts"><span><b>50/50</b> discovery records represented</span><span><b>24/24</b> held-out records represented</span></div>`,caption:'Representability, executability and derivability are measured independently.',label:'Versioned advisory study'},
  42:{kind:'table',html:table(['Retained record','Supported scope'],[['Backend contracts','Transactional state, lifecycle and specialist interchange'],['Native operator','Rendering, density fixtures and paint telemetry'],['18/18 runs','Three production discovery scenarios'],['40/40 runs','Reusable synthetic mechanics'],['Artifact integrity','Staging, verification and rollback contracts']]),caption:'Historical engineering records retain their original verification scopes.',label:'Historical verification'},
  43:{kind:'table',html:table(['Reported autonomous outcome','Evidence class'],[['P.O.O','Reported completion without manual intervention'],['Hard Windows CTF','Reported completion without manual intervention'],['Insane Windows HTB lab','Reported completion without manual intervention'],['Approximately two easy Linux/web labs','Reported completions without manual intervention']]),caption:'Exact outcome logs were not located in the retained record.',label:'Reported field outcomes'},
  44:previous[38],45:previous[39]
 });
 const diagramPages={6:'canonical-state',9:'action-custody',10:'evidence-custody',17:'validated-ai',19:'provider-runtime',22:'engineering-repair',28:'native-interface'};
 Object.entries(diagramPages).forEach(([number,key])=>{visuals[number]={kind:'diagram',html:window.REDSHADES_DIAGRAMS[key],caption:'',selfContained:true};});
 visuals[35].html=`${crop(web('gated'),1536,1170,265,345,116,'Actual pending WebRecon endpoint review gate')}<p class="image-credit">Endpoint review · Qt capture · synthetic fixture</p>${window.REDSHADES_DIAGRAMS['diagnostic-authority']}`;
 // Genuine UI overviews and enlargements preserve the original pixels and state.
 visuals[9].html+=`<div class="capture-strip">${shot('operator-workspace',[20,350,1230,350])}<p class="image-credit">Retained observation history · Qt capture · synthetic fixture</p></div>`;visuals[9].mixed=true;
 visuals[10].html+=`<div class="capture-strip">${shot('webrecon-review',[1835,410,690,220])}<p class="image-credit">Selected evidence detail · Qt capture · synthetic fixture</p></div>`;visuals[10].mixed=true;
 visuals[11].html=`${plate('operator-sessions',[25,340,1210,490])}${table(['Factual frame','Retained dimensions'],[['Identity','Principal, host and session'],['Context','Route, scope and validity'],['Transition','Observed change and cause']])}`;visuals[11].kind='gallery';visuals[11].label='Qt capture + context matrix';
 visuals[17].html=`${plate('operator-ai-settings',[690,415,1180,625])}${window.REDSHADES_DIAGRAMS['validated-ai']}`;visuals[17].mixed=true;
 visuals[20].html=`${plate('operator-runtime-settings',[720,420,1110,525])}${copy(17)}`;visuals[20].mixed=true;visuals[20].label='Qt capture + generation diagram';
 visuals[21]={kind:'gallery',html:`${plate('operator-listeners',[25,360,1240,600])}${table(['Supervisor fact','Meaning'],[['Desired / owned','Required resource and current owner'],['Healthy / applicable','Bounded observation and exact dependency']])}`,caption:'Listener projections remain separate from supervisor ownership and health.',label:'Qt capture + ownership matrix'};
 visuals[26].html+=`<div class="capture-strip">${shot('operator-agents',[30,335,1230,370])}<p class="image-credit">Artifact records · Qt capture · synthetic fixture</p></div>`;visuals[26].mixed=true;
 visuals[30]={kind:'gallery',html:`${overview('operator-workspace')}<p class="image-credit">Evidence workspace · Qt capture · synthetic fixture</p><div class="native-detail-pair"><figure>${shot('operator-sessions',[30,340,1130,500])}<figcaption>Session identity · detail</figcaption></figure><figure>${shot('operator-agents',[30,335,1130,500])}<figcaption>Artifact states · detail</figcaption></figure></div>`,caption:'Native surfaces expose retained evidence, sessions and artifact state.',label:'Qt captures · synthetic fixtures'};
 visuals[33]={kind:'gallery',html:`${overview('network-topology')}<p class="image-credit">Observed topology · Qt capture · synthetic fixture</p>${shot('network-topology',[900,1200,1200,410])}<p class="image-credit">Host and session detail · same capture</p>`,caption:'Exact graph identity connects observed relationships to factual context.',label:'Qt capture · synthetic fixture'};
 visuals[34]={kind:'gallery',html:`${overview('webrecon-overview')}<p class="image-credit">Six linked evidence records · Qt capture · synthetic fixture</p><div class="native-detail-pair"><figure>${shot('webrecon-preview',[385,300,1400,1090])}<figcaption>Retained source preview · synthetic chart</figcaption></figure><figure>${shot('webrecon-overview',[90,200,600,440])}<figcaption>Source card · detail</figcaption></figure></div>`,caption:'Stable record identity connects the map to a retained source preview.',label:'Qt captures · synthetic fixtures'};
 visuals[35].html=`${plate('webrecon-gated',[1835,520,690,295])}${window.REDSHADES_DIAGRAMS['diagnostic-authority']}`;visuals[35].mixed=true;
 visuals[36]={kind:'gallery',html:`${overview('investigation-graph')}<p class="image-credit">Investigation Graph · Qt capture · synthetic fixture</p>${shot('investigation-graph',[1820,235,720,240])}<p class="image-credit">Selected conclusion and its supporting observation · same capture</p>`,caption:'A selected conclusion retains support, counter-evidence and review state.',label:'Qt capture · synthetic fixture'};
 visuals[37]={kind:'gallery',html:`${overview('investigation-workbench')}<p class="image-credit">Investigation Workbench · Qt capture · synthetic fixture</p>${shot('investigation-workbench',[790,360,1350,540])}<p class="image-credit">Canonical detail and provenance · same capture</p>`,caption:'Canonical identity connects searchable records to source detail.',label:'Qt capture · synthetic fixture'};
 const detailed=window.REDSHADES_DETAIL_DIAGRAMS;
 const detailedPages={7:'02-ces-igs-generation-cas',13:'09-source-coordinate-fidelity',18:'04-sic-isw-envelope',22:'06-aep-acp-plo-ownership',23:'06-aep-acp-plo-ownership',25:'10-ci-evidence-custody',28:'08-go-qt-ffi',29:'01-responsibility-map'};
 Object.entries(detailedPages).forEach(([number,key])=>visuals[number]={kind:'diagram',html:detailed[key],caption:'',selfContained:true});
 visuals[9].html=detailed['03-tac-effect-custody']+`<div class="capture-strip">${shot('operator-workspace',[20,350,1230,350])}<p class="image-credit">Retained observation history · Qt capture · synthetic fixture</p></div>`;
 visuals[20].html=plate('operator-runtime-settings',[550,480,850,435])+detailed['05-rck-generation-swap'];
 visuals[35].html=plate('webrecon-gated',[1835,520,690,295])+detailed['07-tmg-scg-bhg'];
 const identityGroups={2:['CES','IGS','EVC','ECT','SIC','DTE'],3:['WFS','PLS','ADS','TAC','ISW'],4:['RCK','AEP','ACP','PLO','RCC','SPR'],5:['TMG','SCG','BHG']};
 const pageAcronyms={6:'CES',7:'IGS',9:'TAC',10:'EVC',11:'ECT',12:'SIC',14:'DTE',16:'WFS',17:'ADS',18:'ISW',19:'RCK',22:'AEP',23:'ACP',38:'RCC'};
 const references={A01:'Authoritative Engagement Architecture',A05:'Execution Graph Lifecycle',A07:'Canonical Specialist Contracts',A08:'Specialist Adapters',A10:'Investigation Attention',A11:'Objective Review Contracts',A12:'Specialist Plugin Registry',A13:'Host Execution Attribution',C02:'Archive Capture Integrity',D01:'Deployment and Process Ownership',G01:'Component Architecture',G03:'Native FFI/API Surfaces',G04:'Reporting Workflow',G07:'Historical Chain Assessment',R01:'Runtime Composition Kernel',R02:'Runtime Lifecycle Adoption',R03:'ACP Vertical Session',R04:'Autonomic Engineering Plane Contract',R05:'Isolated Stage Workers',M01:'Trigger Methodology Graph',M02:'Disclosure Generalization Study',M03:'Shadow Capability Graph',M04:'Advisory Abstraction Research',Q01:'Qt Operator Architecture',Q02:'AttackMap V2 Contract',Q03:'WebRecon Native Parity',Q04:'Investigation Graph and Workbench',Q05:'CAPTCHA Human Gate Contract',E03:'691 Verification Record',E04:'CI Evidence and Cache Custody',E05:'Operator Frontend Evidence',V01:'Chain Simulator and Validation Ladder',V02:'Simulator Architecture',V03:'Simulator Execution Report',V04:'Simulator Live-Escape Audit'};
 references.G05='RedShades Canonical Vocabulary';
 const family=n=>n<6?'System identity':n<15?'State and evidence':n<19?'Supervised execution':n<24?'Runtime and recovery':n<29?'Verification and interfaces':n<39?'Native capabilities':n<44?'Evaluation and results':n<46?'Limits and direction':'Technical indexes';
 const main=document.querySelector('main');main.innerHTML='';
 data.forEach(item=>{
   const n=item.number;const page=document.createElement('section');page.className='page edition-page';page.dataset.shortTitle=item.title;page.dataset.pageNumber=n;page.id=`page-${String(n).padStart(2,'0')}`;
   const shade=window.REDSHADES_PALETTE[n-1];page.dataset.shade=shade.id;page.dataset.accentLuminance=shade.accentLuminance;
   if(n===1){page.classList.add('edition-cover');page.innerHTML=`<div class="edition-cover-top"><strong>RedShades</strong><span>Independent technology<br>September 2026</span></div><h1>RedShades</h1><p class="edition-cover-deck">Durable security orchestration<br>and native operator control.</p><figure class="edition-cover-image"><img src="${capture('operator-workspace').src}" alt="Actual RedShades evidence workspace with synthetic observations"><figcaption>Native evidence workspace · Qt capture · synthetic fixture</figcaption></figure><p class="edition-cover-copy">${esc(item.paragraphs.find(t=>t.length>90)||'Persistent engagement state connects evidence, execution, operator decisions and component recovery.')}</p><p class="edition-cover-credit">Prepared for technical leadership at Cybears, Algeria.</p>`;main.append(page);return;}
   page.innerHTML=`<p class="section-label">RedShades / ${family(n)}</p>${pageAcronyms[n]?`<span class="identity-badge">${pageAcronyms[n]}</span>`:''}<h1>${esc(item.title)}</h1>`;
   if(n>=2&&n<=5){page.classList.add('atlas-page');const entries=item.items;page.insertAdjacentHTML('beforeend',`<p class="print-intro">${esc(item.paragraphs[0])}</p><div class="identity-map">${entries.map(entry=>`<section><strong>${entry.id==='—'?'':entry.id}</strong><div><h3>${esc(entry.title)}</h3><p>${esc(entry.description)}</p></div></section>`).join('')}</div><p class="map-caption">${esc(item.caption)}</p>`);
   } else if(n===50){page.classList.add('references-page');page.insertAdjacentHTML('beforeend',`<div class="complete-references">${item.tables[0].rows.map(([id,title,pages])=>`<p id="ref-${id}"><strong>${id}</strong><span>${title}<small>Narrative ${pages}</small></span></p>`).join('')}</div><div class="review-copy"><p>${esc(item.paragraphs[0])}</p></div>`);
   } else if(n>=46){page.classList.add('index-page');const lookup=item.tables[0];page.insertAdjacentHTML('beforeend',`${item.paragraphs[0]?`<p class="print-intro">${esc(item.paragraphs[0])}</p>`:''}${table(lookup.headers,lookup.rows)}`);
   } else {const visual=visuals[n];page.classList.add(`template-${visual.kind}`);if(visual.selfContained)page.classList.add('diagram-self-contained');if(visual.mixed)page.classList.add('mixed-media');const caption=`<figcaption>${esc(item.caption||visual.caption)}<span>${visual.label||'Conceptual diagram'}</span></figcaption>`;page.insertAdjacentHTML('beforeend',`<p class="print-intro">${esc(item.paragraphs[0])}</p><div class="print-composition"><figure class="technical-visual">${visual.html}${caption}</figure></div>`);if(pageAcronyms[n]&&!visual.selfContained&&visual.kind!=='gallery'){const contract=window.REDSHADES_GLOSSARY.find(e=>e.id===pageAcronyms[n]);page.insertAdjacentHTML('beforeend',`<div class="contract-strip"><div><strong>Input</strong><span>${contract.input}</span></div><div><strong>Output</strong><span>${contract.output}</span></div><div><strong>Authority boundary</strong><span>${contract.boundary}</span></div><p>${contract.evidence}</p></div>`);}}
   page.insertAdjacentHTML('beforeend',`<p class="print-references">${item.references.map(id=>`${id} ${references[id]||''}`).join(' · ')}</p>`);main.append(page);
 });
 const networkPage=main.querySelector('[data-page-number="33"]');
 networkPage.querySelector('.technical-visual').insertAdjacentHTML('beforeend','<div class="context-link"><span><strong>Identity</strong>Exact graph node</span><span><strong>Context</strong>Observed frame reference</span><span><strong>Absence</strong>Unresolved representation</span></div>');
 main.querySelectorAll('.edition-page:not(.dark) svg text[fill="#bfd0cb"]').forEach(t=>t.setAttribute('fill','#4e625c'));
 main.querySelectorAll('svg [stroke]').forEach(e=>{if(e.getAttribute('stroke')!=='none')e.setAttribute('stroke','currentColor');});
 main.querySelectorAll('svg text').forEach(e=>e.setAttribute('fill','currentColor'));
 main.querySelectorAll('svg rect,svg circle').forEach(e=>{if(e.getAttribute('fill')!=='none')e.setAttribute('fill','none');});
 document.querySelector('.toc-drawer')?.remove();document.querySelector('[data-toc-toggle]')?.remove();
 document.querySelector('.reader-brand span').textContent='Technical catalog';
 document.querySelector('.reader-controls').insertAdjacentHTML('afterbegin','<a href="index.html">Website</a>');
})();
