const dialog=document.querySelector('#visual-dialog');let opener;
const stageSearch=document.querySelector('#stage-search'),stageFamily=document.querySelector('#stage-family');
function filterStages(){let count=0;for(const entry of document.querySelectorAll('.atlas-stage')){entry.hidden=!(entry.textContent.toLowerCase().includes(stageSearch.value.toLowerCase())&&(!stageFamily.value||entry.dataset.family===stageFamily.value));if(!entry.hidden)count++;}document.querySelector('#stage-count').textContent=count+' stages';}
stageSearch?.addEventListener('input',filterStages);stageFamily?.addEventListener('change',filterStages);
function openStage(){const entry=document.getElementById(location.hash.slice(1));if(entry?.classList.contains('atlas-stage')){entry.hidden=false;entry.open=true;}}
addEventListener('hashchange',openStage);openStage();
document.querySelectorAll('[data-enlarge]').forEach(link=>link.addEventListener('click',()=>link.focus(),{capture:true}));
document.querySelectorAll('[data-enlarge]').forEach(link=>link.addEventListener('click',event=>{if(!dialog?.showModal)return;event.preventDefault();opener=link;const original=link.querySelector('img');dialog.querySelector('img').src=link.href;dialog.querySelector('img').alt=original.alt;dialog.querySelector('p').textContent=link.closest('figure').querySelector('figcaption').textContent;dialog.showModal()}));
dialog?.querySelector('button').addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>opener?.focus());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
if('IntersectionObserver'in window){const nav=[...document.querySelectorAll('.site-header nav a')];new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){nav.forEach(a=>a.removeAttribute('aria-current'));nav.find(a=>a.hash==='#'+e.target.id)?.setAttribute('aria-current','location')}},{rootMargin:'-15% 0px -55% 0px'}).observe(document.querySelector('#idea'));const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){nav.forEach(a=>a.removeAttribute('aria-current'));nav.find(a=>a.hash==='#'+e.target.id)?.setAttribute('aria-current','location')}},{rootMargin:'-15% 0px -55% 0px'});document.querySelectorAll('section[id].chapter').forEach(s=>observer.observe(s));}
