(() => {
 const dialog=document.getElementById('viewer-dialog'),stage=document.getElementById('viewer-stage'),status=document.getElementById('viewer-status');let origin=null,request=0,loader=null;
 function loadViewer(){return loader||(loader=new Promise((resolve,reject)=>{if(customElements.get('model-viewer'))return resolve();const script=document.createElement('script');script.type='module';script.src='model-viewer.min.js';script.onload=()=>customElements.whenDefined('model-viewer').then(resolve);script.onerror=()=>{loader=null;script.remove();reject(new Error('Viewer failed to load'))};document.head.append(script)}))}
 document.querySelectorAll('.card').forEach(card=>{
  card.querySelectorAll('[data-show]').forEach(button=>button.addEventListener('click',()=>{const reference=button.dataset.show==='reference';card.querySelector('.render').hidden=reference;card.querySelector('.reference').hidden=!reference;card.querySelectorAll('[data-show]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));card.querySelector('.model-label').textContent=reference?'SOURCE PHOTOGRAPH':'ACTUAL 3D RENDER'}));
  card.querySelector('.view-button').addEventListener('click',async event=>{
   origin=event.currentTarget;const token=++request,id=card.dataset.id;document.getElementById('viewer-title').textContent=id+' / '+card.dataset.name;document.getElementById('viewer-download').href='assets/'+id+'/model.glb';document.getElementById('viewer-rhino').href='assets/'+id+'/Samiha6_'+id+'_Rhino7_review_mesh.3dm';stage.replaceChildren();status.textContent='Loading model…';dialog.showModal();document.body.style.overflow='hidden';
   try{await loadViewer();if(token!==request||!dialog.open)return;const model=document.createElement('model-viewer');model.setAttribute('src','assets/'+id+'/model.glb');model.setAttribute('alt','Interactive 3D reconstruction of design '+id+', '+card.dataset.name);model.setAttribute('camera-controls','');model.setAttribute('touch-action','pan-y');model.setAttribute('shadow-intensity','1');model.setAttribute('exposure','1.2');model.setAttribute('camera-orbit','35deg 70deg auto');model.setAttribute('interaction-prompt','auto');model.addEventListener('load',()=>{if(token===request)status.textContent='3D model ready · Assumed 18 mm bore'});model.addEventListener('error',()=>{if(token===request)status.textContent='3D preview unavailable. Download the GLB to open it locally.'});stage.append(model)}catch(e){if(token===request&&dialog.open)status.textContent='3D viewer unavailable. The model is still available to download.'}
  });
 });
 dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{request++;stage.replaceChildren();document.body.style.overflow='';origin?.focus()});document.getElementById('back-top').addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})});
})();
