const fancyQ=(s,c=document)=>c.querySelector(s),fancyQA=(s,c=document)=>[...c.querySelectorAll(s)];

const progress=document.createElement('div');progress.className='page-progress';document.body.append(progress);
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`},{passive:true});

const realGallery=document.createElement('section');realGallery.className='real-photo-rail';realGallery.innerHTML='<div><small>HÔTEL ELCHARK GALLERY</small><h2>Inside the hotel.</h2><p>Rooms and shared spaces from the property gallery.</p></div>'+['room-single-enhanced.webp','room-single-angle-2.webp','room-single-angle-3.webp','room-single-enhanced.webp','room-triple-enhanced.webp','room-double-enhanced.webp','room-twin-angle-2.webp','room-double-angle-2.webp','lobby-enhanced.webp','reception-nocturne-v2.webp'].map((file,i)=>`<img src="../assets/${file}" alt="Hôtel Elchark ${i<8?'guest room':'lobby'} photograph ${i+1}" loading="lazy">`).join('');document.querySelector('main')?.append(realGallery);

if(matchMedia('(pointer:fine)').matches){const cursor=document.createElement('div');cursor.className='fancy-cursor';document.body.append(cursor);addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});fancyQA('a,button,img').forEach(el=>{el.addEventListener('pointerenter',()=>cursor.classList.add('hot'));el.addEventListener('pointerleave',()=>cursor.classList.remove('hot'))})}

const reveal=fancyQA('main section, main article');reveal.forEach(el=>el.classList.add('reveal-ready'));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.12});reveal.forEach(el=>observer.observe(el));

const galleryImages=fancyQA('main img');const lightbox=document.createElement('div');lightbox.className='photo-lightbox';lightbox.innerHTML='<span class="gallery-count"></span><button aria-label="Close gallery">×</button><img><p></p>';document.body.append(lightbox);let activePhoto=0;
function showPhoto(index){activePhoto=(index+galleryImages.length)%galleryImages.length;const source=galleryImages[activePhoto];fancyQ('img',lightbox).src=source.currentSrc||source.src;fancyQ('p',lightbox).textContent=source.alt||source.closest('article')?.querySelector('h3')?.textContent||'Hôtel Elchark';fancyQ('.gallery-count',lightbox).textContent=String(activePhoto+1).padStart(2,'0')+' / '+String(galleryImages.length).padStart(2,'0');lightbox.classList.add('open')}
galleryImages.forEach((img,i)=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','Open real Hôtel Elchark photo');img.addEventListener('click',()=>showPhoto(i));img.addEventListener('keydown',e=>{if(e.key==='Enter')showPhoto(i)})});fancyQ('button',lightbox).onclick=()=>lightbox.classList.remove('open');lightbox.onclick=e=>{if(e.target===lightbox)lightbox.classList.remove('open')};addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')lightbox.classList.remove('open');if(e.key==='ArrowRight')showPhoto(activePhoto+1);if(e.key==='ArrowLeft')showPhoto(activePhoto-1)});

const detail=document.createElement('div');detail.className='room-detail';detail.innerHTML='<div><small>ROOM DETAILS</small><h3></h3></div><p></p><button class="detail-book">Check dates</button><button class="close-detail" aria-label="Close">×</button>';document.body.append(detail);
fancyQA('article').filter(a=>a.querySelector('h3')&&a.querySelector('img')).forEach(card=>{const title=fancyQ('h3',card),desc=fancyQ('p',card)||fancyQ('span',card);title.style.cursor='pointer';title.onclick=()=>{fancyQ('h3',detail).textContent=title.textContent;fancyQ('p',detail).textContent=(desc?.textContent||'Direct confirmation with the hotel.')+' · Wi‑Fi · Air conditioning · TV';detail.classList.add('open')}});fancyQ('.close-detail').onclick=()=>detail.classList.remove('open');fancyQ('.detail-book').onclick=()=>{detail.classList.remove('open');document.querySelector('.reserve')?.showModal()};

if(!matchMedia('(prefers-reduced-motion:reduce)').matches){const heroImg=fancyQ('.hero>img');if(heroImg)addEventListener('scroll',()=>{if(scrollY<innerHeight*1.2)heroImg.style.transform=`translate3d(0,${scrollY*.08}px,0) scale(1.03)`},{passive:true})}

const availability=document.createElement('button');availability.className='availability-pill';availability.innerHTML='<b></b> CHECK AVAILABILITY';availability.onclick=()=>document.querySelector('.reserve')?.showModal();document.body.append(availability);
