(()=>{
const STATIC=['stina.tech','www.stina.tech'].includes(location.hostname)||location.hostname.endsWith('.github.io')||location.protocol==='file:';if(!STATIC)return;
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)],KEY='elchark-demo-reservations',SESSION='elchark_hms_unlocked',now=new Date(),day=n=>new Date(now.getTime()+n*86400000).toISOString().slice(0,10),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),date=v=>v?new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(v)):'—';
const names={new:'Pending confirmation',contacted:'Client contacted',confirmed:'Confirmed',cancellation_requested:'Cancellation requested',checked_in:'Checked in',completed:'Completed',cancelled:'Cancelled',no_show:'No show'},status=v=>`<span class="status ${esc(v)}">${esc(names[v]||v)}</span>`;
function samples(){return[{id:'demo-1042',reference:'ELC-1042',fullName:'Amine B.',email:'guest@example.com',phone:'+213 555 000 000',roomType:'comfort',guests:2,checkIn:day(1),checkOut:day(3),status:'new',createdAt:now.toISOString(),source:'website',history:[{status:'new',at:now.toISOString(),note:'Online request received'}]},{id:'demo-1038',reference:'ELC-1038',fullName:'Sarah K.',email:'sarah@example.com',phone:'+213 555 000 001',roomType:'double',guests:2,checkIn:day(0),checkOut:day(2),status:'confirmed',createdAt:new Date(now-86400000).toISOString(),source:'phone',history:[{status:'confirmed',at:now.toISOString(),note:'Confirmed after telephone call'}]},{id:'demo-1029',reference:'ELC-1029',fullName:'Nabil R.',email:'nabil@example.com',phone:'+213 555 000 002',roomType:'triple',guests:3,checkIn:day(4),checkOut:day(6),status:'cancellation_requested',createdAt:new Date(now-172800000).toISOString(),source:'website',history:[{status:'cancellation_requested',at:now.toISOString(),note:'Cancellation requested'}]}]}
function read(){try{const stored=localStorage.getItem(KEY);if(stored!==null){const rows=JSON.parse(stored);if(Array.isArray(rows))return rows}const seeded=samples();write(seeded);return seeded}catch{return samples()}}function write(rows){localStorage.setItem(KEY,JSON.stringify(rows))}
const OPS_KEY='elchark-hms-operations-v1',defaultRooms=[101,102,103,104,201,202,203,204].map((number,i)=>({id:'room-'+number,number,type:i<3?'Single':i<6?'Double':'Triple',status:i%4===1?'occupied':i%4===2?'cleaning':'vacant'}));
function readOps(){try{const value=JSON.parse(localStorage.getItem(OPS_KEY)||'null');if(value&&Array.isArray(value.rooms))return value}catch{}return{rooms:defaultRooms,expenses:[],tasks:[],shifts:[]}}
function writeOps(value){localStorage.setItem(OPS_KEY,JSON.stringify(value))}
const opsModal=$('#opsModal'),opsForm=$('#opsForm');let opsSubmit=null;
function field(name,label,type='text',extra=''){return`<label>${label}<input name="${name}" type="${type}" ${extra} required></label>`}
function openOps(title,kicker,fields,onSubmit){$('#opsModalTitle').textContent=title;$('#opsModalKicker').textContent=kicker;$('#opsFields').innerHTML=fields;$('.ops-form-error').textContent='';opsSubmit=onSubmit;opsModal.classList.remove('hidden');setTimeout(()=>$('#opsFields input, #opsFields select')?.focus(),0)}
function closeOps(){opsModal.classList.add('hidden');opsForm.reset();opsSubmit=null}
opsForm.onsubmit=e=>{e.preventDefault();try{opsSubmit?.(Object.fromEntries(new FormData(opsForm)));closeOps();renderAll();message('Record saved')}catch(err){$('.ops-form-error').textContent=err.message}};
$('#opsCancel').onclick=closeOps;$('.ops-modal-close').onclick=closeOps;opsModal.onclick=e=>{if(e.target===opsModal)closeOps()};
$('#addWalkIn').onclick=()=>openOps('Walk-in check-in','CURRENT STAYS',field('fullName','Guest name')+field('phone','Phone')+field('roomType','Room type')+field('checkIn','Check-in','date')+field('checkOut','Check-out','date'),b=>{if(new Date(b.checkOut)<=new Date(b.checkIn))throw Error('Check-out must be after check-in');const rows=read(),at=new Date().toISOString();rows.unshift({id:'walkin-'+Date.now(),reference:'ELC-W-'+String(Date.now()).slice(-6),fullName:b.fullName,phone:b.phone,email:'walkin@elchark.local',roomType:b.roomType,guests:1,checkIn:b.checkIn,checkOut:b.checkOut,status:'checked_in',createdAt:at,source:'walk-in',history:[{status:'checked_in',at,note:'Walk-in checked in by reception'}]});write(rows)});
$('#addRoom').onclick=()=>openOps('Add room','ROOM ADMINISTRATION',field('number','Room number','number','min="1"')+field('type','Room type')+'<label>Status<select name="status"><option>vacant</option><option>cleaning</option><option>occupied</option></select></label>',b=>{const ops=readOps();if(ops.rooms.some(r=>String(r.number)===String(b.number)))throw Error('That room already exists');ops.rooms.push({id:'room-'+Date.now(),number:Number(b.number),type:b.type,status:b.status});writeOps(ops)});
$('#addExpense').onclick=()=>openOps('Record expense','DAILY COSTS',field('title','Expense title')+field('amount','Amount (DA)','number','min="0" step="0.01"')+'<label>Remark<textarea name="remark"></textarea></label>',b=>{const ops=readOps();ops.expenses.unshift({id:'expense-'+Date.now(),title:b.title,amount:Number(b.amount),remark:b.remark,at:new Date().toISOString()});writeOps(ops)});
$('#addTask').onclick=()=>openOps('New task','SHIFT HANDOVER',field('action','Task')+field('due','Due date','date')+'<label>Priority<select name="priority"><option>Normal</option><option>High</option><option>Low</option></select></label>',b=>{const ops=readOps();ops.tasks.unshift({id:'task-'+Date.now(),action:b.action,due:b.due,priority:b.priority,done:false});writeOps(ops)});
$('#closeShift').onclick=()=>openOps('Close shift','CASH & PAYMENTS',field('cash','Cash counted (DA)','number','min="0" step="0.01"')+'<label>Handover note<textarea name="note" required></textarea></label>',b=>{const ops=readOps();ops.shifts.unshift({id:'shift-'+Date.now(),cash:Number(b.cash),note:b.note,at:new Date().toISOString()});writeOps(ops)});
function csvCell(v){return'"'+String(v??'').replaceAll('"','""')+'"'}function downloadCsv(name,headers,rows){const csv='\uFEFF'+[headers,...rows].map(row=>row.map(csvCell).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportReservations(){downloadCsv('elchark-reservations.csv',['Reference','Status','Guest','Phone','Room','Check-in','Check-out'],read().map(r=>[r.reference,r.status,r.fullName,r.phone,r.roomType,r.checkIn,r.checkOut]))}
$('#exportArchive').onclick=exportReservations;$('.export').onclick=e=>{e.preventDefault();exportReservations()};
function renderOperationalModules(rows){const ops=readOps(),active=rows.filter(r=>['confirmed','checked_in'].includes(r.status)),archived=rows.filter(r=>['completed','cancelled','no_show'].includes(r.status));$('#stayGrid').innerHTML=active.map(r=>`<article class="ops-card"><small>${names[r.status]||r.status}</small><h3>${esc(r.fullName)}</h3><p>${esc(r.roomType)} · ${date(r.checkIn)} → ${date(r.checkOut)}<br>${esc(r.phone)}</p></article>`).join('')||'<article class="ops-card"><h3>No active stays</h3></article>';$('#roomBoard').innerHTML=ops.rooms.sort((a,b)=>a.number-b.number).map(r=>`<article class="room-tile"><b>${esc(r.number)}</b><span class="${esc(r.status)}">${esc(r.status)}</span><p>${esc(r.type)}</p><button data-room-state="${esc(r.id)}">Change status</button></article>`).join('');$('#expenseGrid').innerHTML=ops.expenses.map(x=>`<article class="ops-card"><small>${date(x.at)}</small><h3>${esc(x.title)}</h3><p>${Number(x.amount).toLocaleString()} DA · ${esc(x.remark||'No remark')}</p></article>`).join('')||'<article class="ops-card"><h3>No expenses recorded</h3></article>';$('#taskGrid').innerHTML=ops.tasks.map(x=>`<article class="ops-card ${x.done?'done':''}"><small>${esc(x.priority)} · ${date(x.due)}</small><h3>${esc(x.action)}</h3><button data-task-toggle="${esc(x.id)}">${x.done?'Reopen':'Mark done'}</button></article>`).join('')||'<article class="ops-card"><h3>No open tasks</h3></article>';const expenses=ops.expenses.reduce((n,x)=>n+Number(x.amount||0),0),last=ops.shifts[0];$('#treasuryGrid').innerHTML=`<article class="finance-card"><small>Recorded expenses</small><b>${expenses.toLocaleString()} DA</b></article><article class="finance-card"><small>Active stays</small><b>${active.length}</b></article><article class="finance-card"><small>Last closed shift</small><b>${last?Number(last.cash).toLocaleString()+' DA':'Open'}</b></article>`;$('#archiveGrid').innerHTML=archived.map(r=>`<article class="ops-card"><small>${names[r.status]||r.status}</small><h3>${esc(r.fullName)}</h3><p>${esc(r.reference)} · ${date(r.checkIn)} → ${date(r.checkOut)}</p></article>`).join('')||'<article class="ops-card"><h3>No archived stays</h3></article>';$$('[data-room-state]').forEach(b=>b.onclick=()=>{const state=readOps(),r=state.rooms.find(x=>x.id===b.dataset.roomState);r.status={vacant:'cleaning',cleaning:'occupied',occupied:'vacant'}[r.status]||'vacant';writeOps(state);renderOperationalModules(read())});$$('[data-task-toggle]').forEach(b=>b.onclick=()=>{const state=readOps(),t=state.tasks.find(x=>x.id===b.dataset.taskToggle);t.done=!t.done;writeOps(state);renderOperationalModules(read())})}
async function verify(value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode('elchark-admin-v2-2026'),iterations:310000,hash:'SHA-256'},key,256);return[...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')==='708a560ea4129a05019d8adb8d0ff4c6cd8fa7859473dfbf8146572d13c169fb'}
function gate(){$('.auth-tabs').hidden=true;$$('[data-auth-form]').forEach(x=>x.classList.remove('active'));$('#showcaseLogin').style.display='block';$('#showcaseLogin').classList.add('active');$('#showcaseLogin').insertAdjacentHTML('beforeend','<p class="demo-security-note">Protected showcase session. Production uses server-side HTTP-only authentication.</p>')}
function openDashboard(){sessionStorage.setItem(SESSION,'1');$('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#adminName').textContent='Reception';$('#adminInitial').textContent='R';renderAll();goView('overview')}
function transition(id,next,note){const rows=read(),r=rows.find(x=>x.id===id);if(!r||next==='confirmed'&&r.status!=='contacted')return;r.status=next;r.updatedAt=new Date().toISOString();r.history=r.history||[];r.history.unshift({status:next,at:r.updatedAt,note});write(rows);renderAll()}
function renderReservations(){let rows=read(),q=($('#searchReservations').value||'').toLowerCase(),f=$('#statusFilter').value;if(q)rows=rows.filter(r=>[r.reference,r.fullName,r.email,r.phone].some(v=>String(v).toLowerCase().includes(q)));if(f!=='all')rows=rows.filter(r=>r.status===f);$('#reservationRows').innerHTML=rows.map(r=>`<tr><td><b>${esc(r.reference)}</b><small>${esc(r.source||'website')}</small></td><td><b>${esc(r.fullName)}</b><small>${esc(r.email)} · ${esc(r.phone)}</small></td><td><b>${date(r.checkIn)} → ${date(r.checkOut)}</b><small>${r.guests||1} guest(s)</small></td><td>${esc(r.roomType)}</td><td>${status(r.status)}</td><td>${date(r.createdAt)}</td><td><div class="reservation-actions"><button data-contact="${esc(r.id)}" ${r.status!=='new'?'disabled':''}>Call completed</button><button class="confirm" data-confirm="${esc(r.id)}" ${r.status!=='contacted'?'disabled':''}>Confirm stay</button></div></td></tr>`).join('');$('#emptyRows').classList.toggle('hidden',rows.length>0);$$('[data-contact]').forEach(b=>b.onclick=()=>transition(b.dataset.contact,'contacted','Receptionist recorded client call'));$$('[data-confirm]').forEach(b=>b.onclick=()=>transition(b.dataset.confirm,'confirmed','Receptionist approved after client confirmation'))}
function renderModules(rows){$('#stayGrid').innerHTML=rows.filter(r=>['confirmed','checked_in'].includes(r.status)).map(r=>`<article class="ops-card"><small>${names[r.status]}</small><h3>${esc(r.fullName)}</h3><p>${esc(r.roomType)} · ${date(r.checkIn)} → ${date(r.checkOut)}<br>${esc(r.phone)}</p></article>`).join('')||'<article class="ops-card"><h3>No active stays</h3></article>';$('#roomBoard').innerHTML=[101,102,103,104,201,202,203,204].map((n,i)=>{const s=i%4===1?'occupied':i%4===2?'cleaning':'vacant';return`<article class="room-tile"><b>${n}</b><span class="${s}">${s}</span><p>${i<3?'Single':i<6?'Double':'Triple'}</p></article>`}).join('');$('#expenseGrid').innerHTML='<article class="ops-card"><small>Today</small><h3>Housekeeping supplies</h3><p>4,200 DA · Receipt attached</p></article><article class="ops-card"><small>Yesterday</small><h3>Maintenance</h3><p>2,500 DA · Approved</p></article>';$('#taskGrid').innerHTML='<article class="ops-card"><small>High priority</small><h3>Room 203 inspection</h3><p>Before 14:00 check-in</p></article><article class="ops-card"><small>Shift handover</small><h3>Confirm tomorrow arrivals</h3><p>2 guests remaining to call</p></article>';$('#treasuryGrid').innerHTML='<article class="finance-card"><small>Payments today</small><b>18,600 DA</b></article><article class="finance-card"><small>Expenses today</small><b>4,200 DA</b></article><article class="finance-card"><small>Expected balance</small><b>14,400 DA</b></article>';$('#archiveGrid').innerHTML='<article class="ops-card"><small>Completed stays</small><h3>Guest archive</h3><p>Search past guests, stays and invoices from one record.</p></article>'}
function renderAll(){const rows=read(),pending=rows.filter(r=>r.status==='new').length,confirmed=rows.filter(r=>r.status==='confirmed').length,cancel=rows.filter(r=>r.status==='cancellation_requested').length;$('#metricTotal').textContent=rows.length;$('#metricNew').textContent=pending;$('#metricConfirmed').textContent=confirmed;$('#metricCancel').textContent=cancel;$('#arrivalsToday').textContent=rows.filter(r=>r.checkIn===day(0)&&!['cancelled','no_show'].includes(r.status)).length;$('#newBadge').textContent=pending;$('#cancelBadge').textContent=cancel;$('#serverClock').textContent='Local showcase · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('#recentList').innerHTML=rows.slice(0,6).map(r=>`<button data-recent-reservation><b>${esc(r.fullName)}<small>${esc(r.reference)}</small></b><span>${date(r.checkIn)} → ${date(r.checkOut)}</span>${status(r.status)}</button>`).join('');$$('[data-recent-reservation]').forEach(b=>b.onclick=()=>goView('reservations'));const audit=rows.flatMap(r=>(r.history||[]).map(h=>({...h,reference:r.reference}))).sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,20),auditHtml=audit.map(a=>`<div class="audit-row"><span>${date(a.at)}</span><b>${esc(a.reference)}</b><span>${esc(a.note||names[a.status])}</span></div>`).join('');$('#miniAudit').innerHTML=auditHtml;$('#auditList').innerHTML=auditHtml;$('#cancellationGrid').innerHTML=rows.filter(r=>r.status==='cancellation_requested').map(r=>`<article class="cancel-card"><small>${esc(r.reference)}</small><h3>${esc(r.fullName)}</h3><p>${date(r.checkIn)} → ${date(r.checkOut)}<br>${esc(r.phone)}</p><button data-cancel="${esc(r.id)}">Approve cancellation →</button></article>`).join('')||'<div class="panel">No cancellation requests.</div>';$$('[data-cancel]').forEach(b=>b.onclick=()=>transition(b.dataset.cancel,'cancelled','Cancellation approved'));renderReservations();renderOperationalModules(rows)}
const meta={overview:['OPERATIONS AT A GLANCE','Overview'],reservations:['PENDING & CONFIRMED','Reservations'],stays:['CURRENT OCCUPANCY','In-house guests'],rooms:['LIVE INVENTORY','Rooms'],expenses:['DAILY COST CONTROL','Expenses'],tasks:['SHIFT WORK','Tasks'],treasury:['CASH & PAYMENTS','Treasury'],archive:['GUEST HISTORY','Guest archive'],cancellations:['PRIORITY ACTION','Cancellations'],audit:['RELIABILITY','Activity log']};function goView(name){$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));$('#viewKicker').textContent=meta[name][0];$('#viewTitle').textContent=meta[name][1]}
$$('[data-view]').forEach(b=>b.onclick=()=>goView(b.dataset.view));$('[data-go-reservations]').onclick=()=>goView('reservations');$('#searchReservations').oninput=renderReservations;$('#statusFilter').onchange=renderReservations;$('#refresh').onclick=renderAll;$('#logout').onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};$('#showcaseLogin').onsubmit=async e=>{e.preventDefault();const btn=$('button',e.target),err=$('.auth-error');btn.disabled=true;err.textContent='Checking…';const ok=await verify(new FormData(e.target).get('password'));btn.disabled=false;if(ok){err.textContent='';openDashboard()}else err.textContent='Invalid password'};gate();if(sessionStorage.getItem(SESSION)==='1')openDashboard();
})();
