(()=>{
const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches,canvases=[...document.querySelectorAll('canvas[data-live-graph]')];
function seeded(seed){let s=seed||1;return()=>((s=Math.imul(48271,s)%2147483647)&2147483647)/2147483647}
function setup(canvas,index){const ctx=canvas.getContext('2d'),rand=seeded(Number(canvas.dataset.seed)||index+11),kind=canvas.dataset.liveGraph,accent=canvas.dataset.accent||'#f04421',base=canvas.dataset.base||'#6e7478';let w=0,h=0,last=0,targetAt=0,series=[72,75,77,79,82,84,86,88],target=[...Array(8)].map((_,i)=>72+i*2),points=[...Array(12)].map(()=>({x:.12+rand()*.76,y:.18+rand()*.7,tx:0,ty:0}));
function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();w=Math.max(280,r.width);h=Math.max(190,r.height);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}
function retarget(t){if(t<targetAt)return;targetAt=t+8000+rand()*4000;if(kind==='line')target=target.map((v,i)=>Math.max(58,Math.min(96,v+(rand()-.44)*9+(i>4?1:0))));else points.forEach(p=>{p.tx=Math.max(.08,Math.min(.92,p.x+(rand()-.5)*.13));p.ty=Math.max(.1,Math.min(.9,p.y+(rand()-.46)*.15))})}
function grid(){ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(128,150,160,.16)';ctx.lineWidth=1;for(let i=0;i<6;i++){let y=18+i*(h-36)/5;ctx.beginPath();ctx.moveTo(34,y);ctx.lineTo(w-16,y);ctx.stroke()}for(let i=0;i<8;i++){let x=34+i*(w-50)/7;ctx.beginPath();ctx.moveTo(x,18);ctx.lineTo(x,h-28);ctx.stroke()}ctx.fillStyle=base;ctx.font='10px Manrope, sans-serif';ctx.fillText(kind==='line'?'VALUE INDEX · 24 MONTH MODEL':'RELATIVE PRICE →',34,h-8)}
function line(t){series=series.map((v,i)=>v+(target[i]-v)*.0025);const draw=(vals,color,offset=0)=>{ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();vals.forEach((v,i)=>{const x=34+i*(w-58)/7,y=h-34-(v+offset-50)*(h-58)/50;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};draw(series,accent);draw(series.map((v,i)=>64+i*.8+Math.sin(t/2600+i)*1.5),base);ctx.fillStyle=accent;ctx.font='700 10px Manrope';ctx.fillText('PORTFOLIO',w-88,22)}
function scatter(){ctx.strokeStyle=accent;ctx.globalAlpha=.35;ctx.beginPath();ctx.moveTo(45,h-42);ctx.lineTo(w-25,28);ctx.stroke();ctx.globalAlpha=1;points.forEach((p,i)=>{p.x+=(p.tx-p.x)*.0025;p.y+=(p.ty-p.y)*.0025;ctx.beginPath();ctx.fillStyle=i<7?accent:base;ctx.arc(34+p.x*(w-58),18+(1-p.y)*(h-54),i<7?4.2:3,0,Math.PI*2);ctx.fill()});ctx.fillStyle=base;ctx.font='10px Manrope';ctx.fillText('QUALITY ↑',6,17)}
function frame(t){if(!w||Math.abs(canvas.getBoundingClientRect().width-w)>2)resize();retarget(t);grid();kind==='line'?line(t):scatter();if(!reduce)requestAnimationFrame(frame)}resize();points.forEach(p=>{p.tx=p.x;p.ty=p.y});frame(0)}
canvases.forEach(setup);
})();
